version: '3.8'
services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: feast
      POSTGRES_USER: feast
      POSTGRES_PASSWORD: feast
    ports:
      - "5432:5432"
